services:
  postgres:
    image: postgres:16
    container_name: tgoliveira11-tech-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tgoliveira11_tech
      POSTGRES_PASSWORD: tgoliveira11_tech
      POSTGRES_DB: tgoliveira11_tech
    ports:
      - "5434:5432"
    volumes:
      - tgoliveira11_tech_postgres_data:/var/lib/postgresql/data

volumes:
  tgoliveira11_tech_postgres_data:
